In [6]:
bool('False')
bool()

False

In [7]:
['hello', 'morning'][bool('')]
#Explanation: The line of code shown above can be simplified to state that ‘hello’ should 
#be printed if the argument passed to the Boolean function amounts to zero, else ‘morning’ will be printed.

'hello'

In [9]:
not(3>4)
not(1&1)
#Explanation: The function not returns true if the argument amounts to false, and false if 
#the argument amounts to true. Hence the first function returns false, and the second function returns false.

False

In [11]:
['f', 't'][bool('spam')]
#Explanation: The line of code can be translated to state that ‘f’ is printed if the argument passed to the Boolean function amount to zero. Else ‘t’ is printed. The argument 
#given to the Boolean function in the above case is ‘spam’, which does not amount to zero. Hence the output is: t.

't'

In [12]:
l=[1, 0, 2, 0, 'hello', '', []]
list(filter(bool, l))

[1, 2, 'hello']

In [13]:
class Truth:
	pass
x=Truth()
bool(x)

True

In [14]:
if (9 < 0) and (0 < -9):
    print("hello")
elif (9 > 0) or False:
    print("good")
else:
    print("bad")

good


In [15]:
not(10<20) and not(10>30)

False

## Bisect algorithm 
Find a position in list where an element needs to be inserted to keep the list sorted.
<br>
bisect(list, num, beg, end): This function returns the position in the sorted list.
<br>
bisect_left(list, num, beg, end)  
bisect_right(list, num, beg, end) 

In [16]:
import bisect 
  
# initializing list 
li = [1, 3, 4, 4, 4, 6, 7] 
  
# using bisect() to find index to insert new element 
# returns 5 ( right most possible index ) 
print ("The rightmost index to insert, so list remains sorted is  : ", end="") 
print (bisect.bisect(li, 4)) 
  
# using bisect_left() to find index to insert new element 
# returns 2 ( left most possible index ) 
print ("The leftmost index to insert, so list remains sorted is  : ", end="") 
print (bisect.bisect_left(li, 4)) 
  
# using bisect_right() to find index to insert new element 
# returns 4 ( right most possible index ) 
print ("The rightmost index to insert, so list remains sorted is  : ", end="") 
print (bisect.bisect_right(li, 4, 0, 4)) 

The rightmost index to insert, so list remains sorted is  : 5
The leftmost index to insert, so list remains sorted is  : 2
The rightmost index to insert, so list remains sorted is  : 4


### Heap queue (or heapq) in Python

Heap data structure is mainly used to represent a priority queue. 
Operations on heap :

1. heapify(iterable) :- This function is used to convert the iterable into a heap data structure. i.e. in heap order.

2. heappush(heap, ele) :- This function is used to insert the element mentioned in its arguments into heap. The order is adjusted, so as heap structure is maintained.

3. heappop(heap) :- This function is used to remove and return the smallest element from heap. The order is adjusted, so as heap structure is maintained.
4. heappushpop(heap, ele) :- This function combines the functioning of both push and pop operations in one statement, increasing efficiency. Heap order is maintained after this operation.

5. heapreplace(heap, ele) :- This function also inserts and pops element in one statement, but it is different from above function. In this, element is first popped, then element is pushed.i.e, the value larger than the pushed value can be returned.
6. nlargest(k, iterable, key = fun) :- This function is used to return the k largest elements from the iterable specified and satisfying the key if mentioned.

7. nsmallest(k, iterable, key = fun) :- This function is used to return the k smallest elements from the iterable specified and satisfying the key if mentioned.

In [17]:
# importing "heapq" to implement heap queue 
import heapq 
  
# initializing list 
li = [5, 7, 9, 1, 3] 
  
# using heapify to convert list into heap 
heapq.heapify(li) 
  
# printing created heap 
print ("The created heap is : ",end="") 
print (list(li)) 
  
# using heappush() to push elements into heap 
# pushes 4 
heapq.heappush(li,4) 
  
# printing modified heap 
print ("The modified heap after push is : ",end="") 
print (list(li)) 
  
# using heappop() to pop smallest element 
print ("The popped and smallest element is : ",end="") 
print (heapq.heappop(li))

The created heap is : [1, 3, 9, 7, 5]
The modified heap after push is : [1, 3, 4, 7, 5, 9]
The popped and smallest element is : 1


In [18]:
import heapq 
  
# initializing list 1 
li1 = [5, 7, 9, 4, 3] 
  
# initializing list 2 
li2 = [5, 7, 9, 4, 3] 
  
# using heapify() to convert list into heap 
heapq.heapify(li1) 
heapq.heapify(li2) 
  
# using heappushpop() to push and pop items simultaneously 
# pops 2 
print ("The popped item using heappushpop() is : ",end="") 
print (heapq.heappushpop(li1, 2)) 
  
# using heapreplace() to push and pop items simultaneously 
# pops 3 
print ("The popped item using heapreplace() is : ",end="") 
print (heapq.heapreplace(li2, 2)) 

The popped item using heappushpop() is : 2
The popped item using heapreplace() is : 3


In [19]:
import heapq 
  
# initializing list  
li1 = [6, 7, 9, 4, 3, 5, 8, 10, 1] 
  
# using heapify() to convert list into heap 
heapq.heapify(li1) 
  
# using nlargest to print 3 largest numbers 
# prints 10, 9 and 8 
print("The 3 largest numbers in list are : ",end="") 
print(heapq.nlargest(3, li1)) 
  
# using nsmallest to print 3 smallest numbers 
# prints 1, 3 and 4 
print("The 3 smallest numbers in list are : ",end="") 
print(heapq.nsmallest(3, li1)) 

The 3 largest numbers in list are : [10, 9, 8]
The 3 smallest numbers in list are : [1, 3, 4]


https://codingcompiler.com/python-interview-questions-answers-1-2-3-4-5-years/
<br>
https://www.w3schools.com/python/python_lambda.asp
<br>
https://www.sanfoundry.com/python-mcqs-tuples/
<br>
According to the itertools docs, it is a “module [that] implements a number of iterator building blocks inspired by constructs from APL, Haskell, and SML… Together, they form an ‘iterator algebra’ making it possible to construct specialized tools succinctly and efficiently in pure Python.”

In [23]:
list(zip([1, 2, 3], ['a', 'b', 'c']))

[(1, 'a'), (2, 'b'), (3, 'c')]

In [24]:
iter([1, 2, 3, 4])

In [25]:
list(map(len, ['abc', 'de', 'fghi']))

[3, 2, 4]

In [26]:
list(map(sum, zip([1, 2, 3], [4, 5, 6])))

[5, 7, 9]

In [27]:
def naive_grouper(inputs, n):
    num_groups = len(inputs) // n
    return [tuple(inputs[i*n:(i+1)*n]) for i in range(num_groups)]
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
naive_grouper(nums, 2)

[(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)]

In [28]:
def naive_grouper(inputs, n):
    num_groups = len(inputs) // n
    return [tuple(inputs[i*n:(i+1)*n]) for i in range(num_groups)]


for _ in naive_grouper(range(100000000), 10):
    pass

In [29]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
iters = [iter(nums)] * 2
list(id(itr) for itr in iters)  # IDs are the same.

[140253771536144, 140253771536144]

itertools
https://realpython.com/python-itertools/
<br>
https://docs.python.org/3.3/library/collections.html

## NUMPY EXAMPLES
<br>
https://www.wisdomjobs.com/e-university/numpy-tutorial-1752/numpy-iterating-over-array-23532.html

In [5]:
import numpy as np 
#numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)
a = np.array([1, 2, 3], dtype = complex) 
print(a)
dt = np.dtype(np.int32) 
print (dt)
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print (a)
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)
a = np.arange(24) 
print (a)
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)
x = np.empty([3,2], dtype = int) 
print (x)
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print (x)
x = [1,2,3] 
a = np.asarray(x) 
print (a)
# ndarray from list of tuples 
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)
x = np.arange(5, dtype = float)
print (x)
x = np.arange(10,20,2) 
print (x)
x = np.linspace(10,20,5) 
print (x)
x = np.linspace(1,2,5, retstep = True) 
print (x) 
a = np.logspace(1.0, 2.0, num = 10) 
print (a)

[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j]
int32
[(10,) (20,) (30,)]
[[1 2]
 [3 4]
 [5 6]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[1 2]
 [3 4]
 [5 6]]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
[1 2 3]
[(1, 2, 3) (4, 5)]
[0. 1. 2. 3. 4.]
[10 12 14 16 18]
[10.  12.5 15.  17.5 20. ]
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [12]:
a = np.arange(10) 
#start, stop ,step
s = slice(2,7,2) 
print (a[s])
a = np.arange(10) 
print (a[2:5])

[2 4 6]
[2 3 4]


In [15]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print ('Our array is:') 
print(a)  
print ('\n')
# this returns array of items in the second column 
print ('The items in the second column are:')  
print (a[...,1]) 
print ('\n')
# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[1,...]) 
print ('\n')
# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [20]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(x)
print(y)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [21]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print ('Our array is:' )
print (x) 
print ('\n')
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
print ('The corner elements of this array are:') 
print (y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [23]:
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print (a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [24]:
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print (a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


In [25]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


In [26]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
print ('First array:' )
print (a) 
print ('\n')  
print ('Second array:') 
print (b) 
print ('\n')  
print ('First Array + Second Array') 
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [27]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')
print ('Modified array is:')
for x in np.nditer(a):
    print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [28]:
a = np.arange(0,60,5) 
a = a.reshape(3,4)
print ('Original array is:') 
print (a) 
print ('\n')
print ('Sorted in C-style order:') 
for x in np.nditer(a, order = 'C'): 
    print (x)  
print ('\n')
print ('Sorted in F-style order:') 
for x in np.nditer(a, order = 'F'): 
    print (x)


Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Sorted in C-style order:
0
5
10
15
20
25
30
35
40
45
50
55


Sorted in F-style order:
0
20
40
5
25
45
10
30
50
15
35
55


In [29]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')
for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=2*x
print ('Modified array is:')
print (a)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [30]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print ('Our array is:')
print (a)  
print ('\n')
print ('Applying amin() function:') 
print (np.amin(a,1)) 
print ('\n')
print ('Applying amin() function again:') 
print (np.amin(a,0)) 
print ('\n')
print ('Applying amax() function:') 
print (np.amax(a)) 
print ('\n')
print ('Applying amax() function again:') 
print (np.amax(a, axis = 0))

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function:
[3 3 2]


Applying amin() function again:
[2 4 3]


Applying amax() function:
9


Applying amax() function again:
[8 7 9]


In [31]:
a = np.array([[3,7],[9,1]])
print ('Our array is:') 
print (a) 
print ('\n')
print ('Applying sort() function:') 
print (np.sort(a)) 
print ('\n') 
print ('Sort along axis 0:') 
print (np.sort(a, axis = 0)) 
print ('\n')
# Order parameter in sort function 
dt = (np.dtype([('name', 'S10'),('age', int)]))
a = (np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt))
print ('Our array is:')
print (a)
print ('\n')
print ('Order by name:') 
print (np.sort(a, order = 'name'))


Our array is:
[[3 7]
 [9 1]]


Applying sort() function:
[[3 7]
 [1 9]]


Sort along axis 0:
[[3 1]
 [9 7]]


Our array is:
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]


Order by name:
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


In [32]:
#A copy of the array object is not made by some of the assignments. The same id() of the original array is used to access.
#The universal identifier of the Python object is returned by the id() which is similar to the pointer.
a = np.arange(6)
print ('Our array is:') 
print (a)
print ('Applying id() function:') 
print (id(a))
print ('a is assigned to b:') 
b = a 
print (b)
print ('b has same id():') 
print (id(b))
print ('Change shape of b:') 
b.shape = 3,2 
print (b)
print ('Shape of a also gets changed:') 
print (a)

Our array is:
[0 1 2 3 4 5]
Applying id() function:
139800995004944
a is assigned to b:
[0 1 2 3 4 5]
b has same id():
139800995004944
Change shape of b:
[[0 1]
 [2 3]
 [4 5]]
Shape of a also gets changed:
[[0 1]
 [2 3]
 [4 5]]


In [34]:
a = np.array([[10,10], [2,3], [4,5]])
print ('Our array is:') 
print (a)
print ('Create a slice:') 
s = a[:, :1] 
print (s) 


Our array is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Create a slice:
[[10]
 [ 2]
 [ 4]]


In [44]:
import numpy.matlib 
import numpy as np
print (np.matlib.empty((2,2))) 
print (np.matlib.rand(3,3))
i = np.matrix('1,2;3,4') 
j = np.asarray(i) 
k = np.asmatrix (j) 
print (k)

[[5.e-324 5.e-324]
 [5.e-324 0.e+000]]
[[0.5317121  0.31996351 0.11421053]
 [0.38291267 0.34884498 0.0377511 ]
 [0.84540635 0.36239427 0.98916704]]
[[1 2]
 [3 4]]


In [41]:
a = np.array([22,87,5,43,56,73,55,54,11,20,51,5,79,31,27]) 
np.histogram(a,bins = [0,20,40,60,80,100]) 
hist,bins = np.histogram(a,bins = [0,20,40,60,80,100]) 
print (hist) 
print (bins) 

[3 4 5 2 1]
[  0  20  40  60  80 100]


In [43]:
import matplotlib.pyplot as plt
a = np.array([22,87,5,43,56,73,55,54,11,20,51,5,79,31,27]) 
plt.hist(a, bins = [0,20,40,60,80,100]) 
plt.title("histogram") 
plt.show()

<Figure size 640x480 with 1 Axes>

In [46]:
print("a"+"bc")
print("abcd"[2:])

abc
cd


In [47]:
str1 = 'hello'
str2 = ','
str3 = 'world'
str1[-1:]

'o'

In [50]:
print (r"\nhello")
print(0xA + 0xB + 0xC)  #hexadecimal

\nhello
33


In [51]:
class father:
    def __init__(self, param):
        self.o1 = param
class child(father):
    def __init__(self, param):
        self.o2 = param
    
obj = child(22)
print ("%d %d" % (obj.o1, obj.o2))

AttributeError: 'child' object has no attribute 'o1'

In [52]:
#Strings cannot be modified.
example = "snow world"
example[3] = 's'
print (example)

TypeError: 'str' object does not support item assignment

In [ ]:
To concatenate two strings to a third what statements are applicable ?
s3 = s1.__add__(s2)

In [53]:
print(chr(ord('b')+1))

c


In [54]:
print(format("Welcome", "10s"), end = '#')
print(format(111, "4d"), end = '#')
print(format(924.656, "3.2f"))

Welcome   # 111#924.66


In [55]:
d = {0: 'a', 1: 'b', 2: 'c'}
for x, y in d.items():
    print(x, y)

0 a
1 b
2 c


In [56]:
d = {0: 'a', 1: 'b', 2: 'c'}
for x in d.keys():
    print(d[x])

a
b
c


In [57]:
d = {0, 1, 2}
for x in d:
    print(d.add(x))

None
None
None


In [58]:
print("abc. DEF".capitalize())

Abc. def


In [60]:
print('*', "abcdef".center(7), '*')
#Padding is done towards the left-hand-side first when the final 
#string is of odd length. Extra spaces are present since we haven’t overridden the value of sep.

*  abcdef *


In [61]:
print("abcdef".center(7, 1))

TypeError: The fill character must be a unicode character, not int

In [62]:
print("xyyzxyzxzxyy".count('yy', 1))
#Explanation: Counts the number of times the substring 
#‘yy’ is present in the given string, starting from position 1.

2


In [63]:
print('abc'.encode())

b'abc'


In [64]:
print("ab\tcd\tef".expandtabs(4))

ab  cd  ef


In [65]:
print("abcdef".find("cd") == "cd" in "abcdef")

False


In [66]:
print('The sum of {0} and {1} is {2}'.format(2, 10, 12))

The sum of 2 and 10 is 12


In [67]:
print('{:,}'.format(1112223334))

1,112,223,334


In [68]:
print('{:#}'.format(1112223334))

1112223334


In [69]:
print('ab12'.isalnum())

True


In [70]:
#Even keywords are considered as valid identifiers.
print('for'.isidentifier())

True


In [71]:
print('''\tfoo'''.lstrip())

foo


In [72]:
print('xyxxyyzxxy'.lstrip('xyy'))

zxxy


In [74]:
#The string is split into three parts by partition.
print('abcdef'.partition('cd'))

('ab', 'cd', 'ef')


In [76]:
#The first 0 occurrences of the given substring are replaced.
print('xyyxyyxyxyxxy'.replace('xy', '12', 0))
print('xyyxyyxyxyxxy'.replace('xy', '12', 1))

xyyxyyxyxyxxy
12yxyyxyxyxxy


In [77]:
print('abcdefcdghcd'.split('cd', -1))

['ab', 'ef', 'gh', '']


In [78]:
print('ab\ncd\nef'.splitlines())

['ab', 'cd', 'ef']


In [79]:
print('abcd'.translate('a'.maketrans('abc', 'bcd')))

bcdd


In [80]:
print('abcd'.translate({97: 98, 98: 99, 99: 100}))

bcdd


In [81]:
print('+99'.zfill(5))

+0099


In [82]:
list("a#b#c#d".split('#'))

['a', 'b', 'c', 'd']

In [83]:
myList = [1, 5, 5, 5, 5, 1]
max = myList[0]
indexOfMax = 0
for i in range(1, len(myList)):
    if myList[i] > max:
        max = myList[i]
        indexOfMax = i
print(indexOfMax)

1


In [84]:
myList = [1, 2, 3, 4, 5, 6]
for i in range(1, 6):
    myList[i - 1] = myList[i]
    for i in range(0, 6): 
        print(myList[i], end = " ")

2 2 3 4 5 6 2 3 3 4 5 6 2 3 4 4 5 6 2 3 4 5 5 6 2 3 4 5 6 6 

In [85]:
veggies = ['carrot', 'broccoli', 'potato', 'asparagus']
veggies.insert(veggies.index('broccoli'), 'celery')
print(veggies)

['carrot', 'celery', 'broccoli', 'potato', 'asparagus']


In [87]:
m = [[x, y] for x in range(0, 4) for y in range(0, 4)]
print(m)

[[0, 0], [0, 1], [0, 2], [0, 3], [1, 0], [1, 1], [1, 2], [1, 3], [2, 0], [2, 1], [2, 2], [2, 3], [3, 0], [3, 1], [3, 2], [3, 3]]


In [88]:
matrix = [[1, 2, 3, 4],
          [4, 5, 6, 7],
          [8, 9, 10, 11],
          [12, 13, 14, 15]]
for i in range(0, 4):
    print(matrix[i][1], end = " ")

2 5 9 13 

In [95]:
data = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

def ttt(m):
    v = m[0][0]

    for row in m:
        for element in row:
            if v < element: 
                v = element
            return (v)
print(ttt(data[0]))

1


In [96]:
a=[10,23,56,[78]]
b=list(a)
a[3][0]=95
a[1]=34
print(b)

[10, 23, 56, [95]]


In [97]:
s="a@b@c@d"
a=list(s.partition("@"))
print(a)
b=list(s.split("@",3))
print(b)

['a', '@', 'b@c@d']
['a', 'b', 'c', 'd']


In [98]:
a=[1,2,3,4]
b=[sum(a[0:x+1]) for x in range(0,len(a))]
print(b)

[1, 3, 6, 10]


In [99]:
word1="Apple"
word2="Apple"
list1=[1,2,3]
list2=[1,2,3]
print(word1 is word2)
print(list1 is list2)

True
False


In [102]:
x = [i**+1 for i in range(3)]; print(x);

[0, 1, 2]


In [105]:
l1=[1,2,3]
l2=[4,5,6]
[x*y for x in l1 for y in l2]

[4, 5, 6, 8, 10, 12, 12, 15, 18]

In [106]:
l1=[1,2,3]
l2=[4,5,6]
[x*y for x in l1 for y in l2]

[4, 5, 6, 8, 10, 12, 12, 15, 18]

In [107]:
t=32.00
[round((x-32)*5/9) for x in t]

TypeError: 'float' object is not iterable

In [108]:
for i in range(1, 101):
	if int(i*0.5)==i*0.5:
		print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [109]:
l=["good", "oh!", "excellent!", "#450"]
[n for n in l if n.isalpha() or n.isdigit()]

['good']

In [110]:
A = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]
[A[row][1] for row in (0, 1, 2)]

[2, 5, 8]

In [112]:
l=[[1, 2, 3], [4, 5, 6]]
for i in range(len(l)):
	for j in range(len(l[i])):
		l[i][j]+=10
l

[[11, 12, 13], [14, 15, 16]]

In [113]:
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
B = [[3, 3, 3],
     [4, 4, 4],
     [5, 5, 5]]
[[col1 * col2 for (col1, col2) in zip(row1, row2)] for (row1, row2) in zip(A, B)]

[[3, 6, 9], [16, 20, 24], [35, 40, 45]]

In [114]:
t=(1,2,4,3)
t[1:-1]

(2, 4)

In [115]:
d = {"john":40, "peter":45}
d["john"]

40

In [1]:
t = (1, 2, 4, 3, 8, 9)
[t[i] for i in range(0, len(t), 2)]

[1, 4, 8]

In [4]:
numberGames = {}
numberGames[(1,2,4)] = 8
numberGames[(4,2,1)] = 10
numberGames[(1,2)] = 12
print(numberGames)
sum = 0
for k in numberGames:
    sum += numberGames[k]
    print (len(numberGames) + sum)
#Explanation: Tuples can be used for keys into dictionary. The tuples 
#can have mixed length and the order of the items in the tuple is considered when comparing the equality of the keys.

{(1, 2, 4): 8, (4, 2, 1): 10, (1, 2): 12}
11
21
33


In [ ]:
a=(2,3,4)
sum(a,3)
#Explanation: In the above case, 3 is the starting value to which the sum of the tuple is added to.

In [ ]:
a=(0,1,2,3,4)
b=slice(0,2)
a[b]
#The method illustrated in the above piece of code is that of naming of slices.

In [5]:
# A namedtuple assigns names, as well as the numerical index, to each member.
import collections
a=collections.namedtuple('a',['i','j'])
obj=a(i=4,j=7)
obj

a(i=4, j=7)

In [6]:
set([[1,2],[3,4]])
#The argument given for the set must be an iterable.

TypeError: unhashable type: 'list'

In [7]:
a = [5,5,6,7,7,7]
b = set(a)
def test(lst):
    if lst in b:
        return 1
    else:
        return 0
for i in  filter(test, a):
    print(i,end=" ")
#Explanation: The filter function will return all the values from list a which are true when passed to function test. 
#Since all the members of the set are non-duplicate
#members of the list, all of the values will return true. Hence all the values in the list are printed.

5 5 6 7 7 7 

In [8]:
a={5,4}
b={1,2,4,5}
a<b
#Explanation: a<b returns True if a is a proper subset of b.

True

In [9]:
a={"a":1,"b":2,"c":3}
b=dict(zip(a.values(),a.keys()))
b

{1: 'a', 2: 'b', 3: 'c'}

In [10]:
a=10
b=20
def change():
    global b
    a=45
    b=56
change()
print(a)
print(b)

10
56


https://realpython.com/working-with-files-in-python/

In [11]:
# Binary search
def binary_search(item_list,item):
    first = 0
    last = len(item_list)-1
    found = False
    while( first<=last and not found):
        mid = (first + last)//2
        if item_list[mid] == item :
            found = True
        else:
            if item < item_list[mid]:
                last = mid - 1
            else:
                first = mid + 1    
    return found
    
print(binary_search([1,2,3,5,8], 6))
print(binary_search([1,2,3,5,8], 5))

False
True


In [12]:
# Selection search
import sys 
A = [64, 25, 12, 22, 11] 
for i in range(len(A)): 
      
    # Find the minimum element in remaining  
    # unsorted array 
    min_idx = i 
    for j in range(i+1, len(A)): 
        if A[min_idx] > A[j]: 
            min_idx = j 
              
    # Swap the found minimum element with  
    # the first element         
    A[i], A[min_idx] = A[min_idx], A[i] 
# Driver code to test above 
print ("Sorted array") 
for i in range(len(A)): 
    print("%d" %A[i]),  

Sorted array
11
12
22
25
64


In [14]:
# Insertion sort
def insertionSort(arr): 
  
    # Traverse through 1 to len(arr) 
    for i in range(1, len(arr)): 
  
        key = arr[i] 
  
        # Move elements of arr[0..i-1], that are 
        # greater than key, to one position ahead 
        # of their current position 
        j = i-1
        while j >=0 and key < arr[j] : 
                arr[j+1] = arr[j] 
                j -= 1
        arr[j+1] = key 
# Driver code to test above 
arr = [64, 25, 12, 22, 11] 
insertionSort(arr) 
for i in range(len(arr)): 
    print ("%d" %arr[i]) 

11
12
22
25
64


In [25]:
## Quick sort
def partition(arr,low,high): 
    i = ( low-1 )         # index of smaller element 
    pivot = arr[high]     # pivot 
  
    for j in range(low , high): 
  
        # If current element is smaller than or 
        # equal to pivot 
        if   arr[j] <= pivot: 
          
            # increment index of smaller element 
            i = i+1 
            arr[i],arr[j] = arr[j],arr[i] 
  
    arr[i+1],arr[high] = arr[high],arr[i+1] 
    return ( i+1 ) 
  
# The main function that implements QuickSort 
# arr[] --> Array to be sorted, 
# low  --> Starting index, 
# high  --> Ending index 
  
# Function to do Quick sort 
def quickSort(arr,low,high): 
    if low < high: 
          # pi is partitioning index, arr[p] is now 
        # at right place 
        pi = partition(arr,low,high) 
  
        # Separately sort elements before 
        # partition and after partition 
        quickSort(arr, low, pi-1) 
        quickSort(arr, pi+1, high) 
  
# Driver code to test above 
arr = [10, 7, 8, 9, 1, 5] 
n = len(arr) 
quickSort(arr,0,n-1) 
print ("Sorted array is:") 
for i in range(n): 
    print ("%d" %arr[i]), 

Sorted array is:
1
5
7
8
9
10


In [16]:
def factorial(n):
    print("factorial has been called with n = " + str(n))
    if n == 1:
        return 1
    else:
        res = n * factorial(n-1)
        print("intermediate result for ", n, " * factorial(" ,n-1, "): ",res)
        return res	

print(factorial(5))


factorial has been called with n = 5
factorial has been called with n = 4
factorial has been called with n = 3
factorial has been called with n = 2
factorial has been called with n = 1
intermediate result for  2  * factorial( 1 ):  2
intermediate result for  3  * factorial( 2 ):  6
intermediate result for  4  * factorial( 3 ):  24
intermediate result for  5  * factorial( 4 ):  120
120


In [20]:
## Palindrome
def reverse(s): 
    return s[::-1] 
  
def isPalindrome(s): 
    # Calling reverse function 
    rev = reverse(s) 
  
    # Checking if both string are equal or not 
    if (s == rev): 
        return True
    return False
  
  
# Driver code 
s = "malayalam"
ans = isPalindrome(s) 
  
if ans == 1: 
    print("Yes") 
else: 
    print("No") 

Yes


In [21]:
def power(x, y): 
  
    if (y == 0): return 1
    elif (int(y % 2) == 0): 
        return (power(x, int(y / 2)) *
               power(x, int(y / 2))) 
    else: 
        return (x * power(x, int(y / 2)) *
                   power(x, int(y / 2))) 
  
# Driver Code 
x = 2; y = 3
print(power(x, y)) 

8


In [23]:
import turtle

def drawTriangle(points,color,myTurtle):
    myTurtle.fillcolor(color)
    myTurtle.up()
    myTurtle.goto(points[0][0],points[0][1])
    myTurtle.down()
    myTurtle.begin_fill()
    myTurtle.goto(points[1][0],points[1][1])
    myTurtle.goto(points[2][0],points[2][1])
    myTurtle.goto(points[0][0],points[0][1])
    myTurtle.end_fill()

def getMid(p1,p2):
    return ( (p1[0]+p2[0]) / 2, (p1[1] + p2[1]) / 2)

def sierpinski(points,degree,myTurtle):
    colormap = ['blue','red','green','white','yellow',
                'violet','orange']
    drawTriangle(points,colormap[degree],myTurtle)
    if degree > 0:
        sierpinski([points[0],
                        getMid(points[0], points[1]),
                        getMid(points[0], points[2])],
                   degree-1, myTurtle)
        sierpinski([points[1],
                        getMid(points[0], points[1]),
                        getMid(points[1], points[2])],
                   degree-1, myTurtle)
        sierpinski([points[2],
                        getMid(points[2], points[1]),
                        getMid(points[0], points[2])],
                   degree-1, myTurtle)

def main():
   myTurtle = turtle.Turtle()
   myWin = turtle.Screen()
   myPoints = [[-100,-50],[0,100],[100,-50]]
   sierpinski(myPoints,3,myTurtle)
   myWin.exitonclick()

main()
